name: Publish Judgehost
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Judgehost
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: rmartinsanta/judgehost
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
